upstream neto_app { server a71deaf3a81d:9000; }

server {
    listen 80;
    server_name app.netoia.cloud;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.netoia.cloud;
    ssl_certificate /etc/letsencrypt/live/netoia.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/netoia.cloud/privkey.pem;
    
    location /api/ {
        fastcgi_pass neto_app;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/neto/backend/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_script_name;
        include fastcgi_params;
    }
    location / {
        proxy_pass http://172.18.0.2:5173;
    }
}